name: Before Merge

on:
    pull_request:
        type: [opened, reopened]
        branches: [master]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Install
              run: |
                  npm i pnpm -g
                  pnpm install --frozen-lockfile

            - name: Run test
              run: pnpm test

            - name: Run typescript check
              run: pnpm vue-tsc --noEmit
            
            - name: Run lint
              run: pnpm lint
