name: Docs Deploy

on:
    push:
        branches:
            - master
    schedule:
      - cron: "0 0 * * *"

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Install
              run: |
                  npm i pnpm -g
                  pnpm install --frozen-lockfile

            - name: Build
              run: pnpm docs:build

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUBTOKEN }}
                  publish_dir: docs/.vitepress/dist
